---
name: "CI/CD"
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v3"
      - name: "Linting"
        run: "make lint"
  build:
    runs-on: "ubuntu-20.04"
    needs:
      - "lint"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v3"
      - name: "Build for branches"
        run: "make tag=${{ github.ref_name }} build"
      - name: "Push the image to the repository"
        run: "make tag=${{ github.ref_name }} push"
  test:
    runs-on: "ubuntu-20.04"
    needs:
      - "build"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v3"
      - name: "Pull the image"
        run: "make tag=${{ github.ref_name }} pull"
      - name: "Run tests"
        run: "make test"
  deploy:
    runs-on: "ubuntu-20.04"
    needs:
      - "test"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v3"
      - name: "Pull the image"
        run: "make tag=${{ github.ref_name }} deploy"
